apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-clean-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path