apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-complete-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: complete-java-pipeline-run
  namespace: default
spec:
  pipelineRef:
    name: complete-java-pipeline
  params:
    - name: repo-url
      value: "https://github.com/milymoreno/creating-cicd-pipelines-with-tekton-2"
    - name: revision
      value: main
    - name: image-name
      value: "demo-java-app"
    - name: image-tag
      value: "v1.0.0"
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: tekton-complete-pvc