apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-java-pipeline-5-tasks
  namespace: default
spec:
  description: Demo pipeline with 5 tasks for KCD presentation
  params:
    - name: repo-url
      type: string
      description: The git repository URL to clone from
      default: "https://github.com/milymoreno/creating-cicd-pipelines-with-tekton-2"
    - name: revision
      type: string
      description: The git revision to clone
      default: main
    - name: app-name
      type: string
      description: Application name
      default: kcd-demo-app
    - name: environment
      type: string
      description: Target environment
      default: development
  workspaces:
    - name: shared-data
      description: Shared workspace for pipeline tasks
  tasks:
    # 1. Clone source code
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)

    # 2. Build with Maven (compile + test + package)
    - name: build-artifact
      taskRef:
        name: maven-simple
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: GOALS
          value: ["clean", "compile", "test", "package"]
      runAfter:
        - fetch-source

    # 3. Run explicit JUnit tests
    - name: run-tests
      taskRef:
        name: junit-test
      workspaces:
        - name: source
          workspace: shared-data
      runAfter:
        - build-artifact

    # 4. Copy JAR artifact
    - name: copy-jar
      taskRef:
        name: copy-jar-artifact
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: app-name
          value: $(params.app-name)
      runAfter:
        - run-tests

    # 5. Deploy application
    - name: deploy-app
      taskRef:
        name: deploy-artifact-to-ibm-cloud-functions
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: APP_NAME
          value: $(params.app-name)
        - name: ENVIRONMENT
          value: $(params.environment)
      runAfter:
        - copy-jar