apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: junit-test
spec:
  description: Run JUnit tests
  workspaces:
  - name: source
    description: The workspace containing the source code
  steps:
  - name: run-tests
    image: maven:3.8.6-openjdk-11
    workingDir: $(workspaces.source.path)
    script: |
      #!/bin/bash
      echo "Running JUnit tests..."
      if [ -f pom.xml ]; then
        mvn test
      else
        echo "No pom.xml found, skipping tests"
      fi
      echo "Tests completed successfully"