apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: junit-test
spec:
  description: Ejecuta pruebas JUnit con Maven y expone la ruta del reporte.
  params:
    - name: maven-image
      type: string
      default: maven:3.9-eclipse-temurin-17
  workspaces:
    - name: source
      description: Código fuente de la aplicación (clonado previamente)
  results:
    - name: test-result
      description: "OK si las pruebas pasan."
    - name: report-path
      description: "Ruta a los reportes JUnit (Surefire)."
  steps:
    - name: run-tests
      image: $(params.maven-image)
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo ">> Running Maven tests..."
        mvn -B test
        echo -n "OK" > "$(results.test-result.path)"
        echo -n "$(workspaces.source.path)/target/surefire-reports" > "$(results.report-path.path)"